# Generated by Django 4.0.1 on 2022-05-23 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dev_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=40)),
                ('devid', models.TextField()),
                ('voltage', models.TextField(null=True)),
                ('active_power_W', models.TextField(null=True)),
                ('apparent_power_VA', models.TextField(null=True)),
                ('active_energy_Wh', models.TextField(null=True)),
                ('apparent_energy_VAh', models.TextField(null=True)),
                ('phase_current', models.TextField(null=True)),
                ('neutral_current', models.TextField(null=True)),
                ('frequency', models.TextField(null=True)),
                ('pf', models.TextField(null=True)),
                ('meter_time', models.TextField(null=True)),
            ],
            options={
                'db_table': 'dev_data',
            },
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('organization', models.CharField(max_length=30)),
                ('privilege', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user_detail',
            },
        ),
    ]
